### ISSUE TITLE
local variable 'trans' referenced before assignment

### ISSUE THREAD

**Issue by scy5335** [HLinChen/VCR-GauS#1]
Line 239 In dataset_readers.py, the trans isn't defined before using it. How can I fixed this bug? 
![image](https://github.com/user-attachments/assets/2ce36ca0-be60-499f-ad82-37905ae94279)

**Comment by HLinChen** [comment]
Do you train on custom data?

**Comment by scy5335** [comment]
No. I train on mip-nerf360 datasets.

**Comment by HLinChen** [comment]
I have just pushed an update. Please run git pull to get the latest version.

**Comment by scy5335** [comment]
> I have just pushed an update. Please run git pull to get the latest version.

If "meta_fname" is not existed, the parameter "trans" of "filter_point_cloud" will be still undefined?

**Comment by HLinChen** [comment]
It will be generated in line 252.

**Comment by scy5335** [comment]
this code is both in line 239 and line 283, the origin mip-nerf360 dataset don't have meta.json and points3D.ply. In line 239, the code will cause error.
![image](https://github.com/user-attachments/assets/d14ed558-bea1-47be-8f9b-b89458c00e8e)
![image](https://github.com/user-attachments/assets/ba077d90-bb77-41e6-8ed4-910ab3d87a5c)

**Comment by HLinChen** [comment]
Fixed. Just comment this line.
