### ISSUE TITLE
Questions about backward.cu

### ISSUE THREAD

**Issue by scy5335** [HLinChen/VCR-GauS#5]
Why are there both accum_normal_rec and accum_normal_rec2? Where can I get proof of that? 
![image](https://github.com/user-attachments/assets/d17fe13d-8ac2-4fae-b145-35e53ad78ee0)

**Comment by HLinChen** [comment]
This is the gradient backpropagation of depth for alpha. And the normal is the similar. Hope it can help you.
<img width="876" alt="image" src="https://github.com/user-attachments/assets/a3b2fe5d-015f-4c60-9988-e7f69939cdfa">

**Comment by scy5335** [comment]
Thanks for your reply. Have a nice day!
